version: "3.8"
services:
  database:
    restart: always
    image: postgres:15.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shortener_potion_dev
